petshop/Areas/Admin/Controllers/PetController.cs
using Miau.Areas.Admin.Model;
using Miau.DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Miau.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class PetController : Controller
    {

        private AppDbContext _context;



        public PetController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            var pets = _context.Pets.ToList();



            return View(pets);
        }

        public IActionResult Create()
        {




            return View();
        }
        [HttpPost]
        public IActionResult Create(Pet model)
        {
            if (string.IsNullOrEmpty(model.CustomerName))
            {
                return RedirectToAction("Index");
            }
            if (string.IsNullOrEmpty(model.AnimalName))
            {
                return RedirectToAction("Index");
            }
            if (string.IsNullOrEmpty(model.Mail))
            {
                return RedirectToAction("Index");
            }
            if (string.IsNullOrEmpty(model.Note))
            {
                return RedirectToAction("Index");
            }
           
            var pet = new Pet
            {
                CustomerName = model.CustomerName,
                AnimalName = model.AnimalName,
                Mail = model.Mail,
                Note = model.Note

            };
            _context.Pets.Add(pet);

            _context.SaveChanges();
            return RedirectToAction("Index");
          
        }
        public IActionResult Update(int id)
        {
            var pet = _context.Pets.Find(id);



            return View(pet);
        }

        [HttpPost]
        public IActionResult Update( int id, Pet model)
        {
            var pet = _context.Pets.Find(id);
            pet.CustomerName = model.CustomerName;
            pet.AnimalName = model.AnimalName;
            pet.Mail = model.Mail;
            pet.Note = model.Note;
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        
        public IActionResult Delete(int id)
        {
            var pet = _context.Pets.Find(id);
            _context.Pets.Remove(pet);
            _context.SaveChanges();
            return RedirectToAction("Index");

        }



    }
}
      
    

petshop/Areas/Admin/Views/Pet/Create.cshtml
@model Pet
<form asp-controller="Pet" asp-action="Create" method="post">
    <input placeholder="CustomerName" asp-for="CustomerName" />
    <input placeholder="AnimalName" asp-for="AnimalName" />
    <input placeholder="Mail" asp-for="Mail" />
    <input placeholder="Note" asp-for="Note" />
    <button type="submit"> Submit</button>
</form>

petshop/Areas/Admin/Views/Pet/Index.cshtml
@model List<Pet>
@{
    ViewData["Title"] = "Index";
}

<table class="table">
    <thead>
        <tr>
            <th scope="col">Id</th>
            <th scope="col">CustomerName</th>
            <th scope="col">AnimalName</th>
            <th scope="col">Mail</th>
            <th scope="col">Note</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var pet in Model) { 
        <tr>
            <th scope="row">@pet.Id</th>
            <td>@pet.CustomerName</td>
            <td>@pet.AnimalName</td>
            <td>@pet.Mail</td>
            <td>@pet.Note</td>
            <td>
                <a asp-controller="Pet" asp-action="Update" asp-route-id="@pet.Id"><button>Update</button></a>
                <a asp-controller="Pet" asp-action="Delete" asp-route-id="@pet.Id"><button>Delete</button></a>
            </td>
        </tr>
        }
       
        
    </tbody>
</table>

petshop/Areas/Admin/Views/Pet/Update.cshtml
@model Pet
<form asp-controller="Pet" asp-action="Update" method="post" asp-route-id="@Model.Id">
    <input placeholder="CustomerName" asp-for="CustomerName" />
    <input placeholder="AnimalName" asp-for="AnimalName" />
    <input placeholder="Mail" asp-for="Mail" />
    <input placeholder="Note" asp-for="Note" />
    <button type="submit"> Submit</button>
</form>